# Generated by Django 5.0.6 on 2024-06-03 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogcategorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
