# Generated by Django 5.0.6 on 2024-06-03 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogmodel_created_at_blogmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
