# Generated by Django 5.0.6 on 2024-06-03 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='img_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
