# Generated by Django 5.0.6 on 2024-06-03 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogmodel_img_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
