# Generated by Django 5.0.6 on 2024-06-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blogmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='img_description',
        ),
    ]
